### ISSUE TITLE
Implement like and comment button using AJAX

### ISSUE THREAD

**Issue by Nancy-Chauhan** [snowflake-app/snowflake#12]
Currently, we refresh the full page which isn't very ideal.

### Tasks

- [ ] Make like and comment endpoint return a JSON response when `Accept` header is set to `application/json`
- [ ] Submit like/dislike form over AJAX on button press
- [ ] Submit like/dislike form over AJAX on button press
